name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  easy_stepper:
    path: ../
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  intl: ^0.17.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
